print("                                     ")
name = input("Qual o seu nome? ")
print("                                     ")
id = input("Qual sua idade? ")
print("                                     ")
money = float(input("Qual o seu salário? "))
print("                                     ")
aumento = float(input("Qual a pocentagem de aumento que teve esse ano? "))
print("                                     ")
dimdim = (money+((money*aumento)/100))
print(f"Oi {name}, você tem {id} anos e recebe por mês um salário no valor de R${dimdim}.")
