print("                                     ")
print("                                     ")
n1 = float(input("Digite o primeiro número: "))
print("                                     ")
n2 = float(input("Digite o segundo número: "))
print("                                     ")
print("                                     ")
print(f"A soma dos números é {n1+n2}")
print(f"A subtração dos números é {n1-n2}")
print(f"A dmultiplicação dos números é {n1*n2}")
print(f"A divisão dos números é {n1/n2}")
